export const SET_CATEGORY = "SET_CATEGORY";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY="UPDATE_CATEGORY";
export const UPDATE_CATEGORY_ITEM="UPDATE_CATEGORY_ITEM";
export const ADD_CATEGORY_ITEM = "ADD_CATEGORY_ITEM";
export const DELETE_CATEGORY_ITEM = "DELETE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const SET_BRAND = "SET_BRAND";
export const ADD_BRAND = "ADD_BRAND";
export const UPDATE_BRAND="UPDATE_BRAND";
export const UPDATE_BRAND_ITEM="UPDATE_BRAND_ITEM";
export const ADD_BRAND_ITEM = "ADD_BRAND_ITEM";
export const DELETE_BRAND_ITEM = "DELETE_BRAND_ITEM";
export const DELETE_BRAND = "DELETE_BRAND";

export const SET_PRODUCT = "SET_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT="UPDATE_PRODUCT";
export const UPDATE_PRODUCT_ITEM="UPDATE_PRODUCT_ITEM";
export const ADD_PRODUCT_ITEM = "ADD_PRODUCT_ITEM";
export const DELETE_PRODUCT_ITEM = "DELETE_PRODUCT_ITEM";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
